<?php
/**
 * FfIPrepInstruction
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  MPSolutions\AmznSellingPartnerApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Selling Partner API for Fulfillment Inbound
 *
 * The Selling Partner API for Fulfillment Inbound lets you create applications that create and update inbound shipments of inventory to Amazon's fulfillment network.
 *
 * The version of the OpenAPI document: v0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.0.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace MPSolutions\AmznSellingPartnerApi\Models\FulfillmentInbound;
use \MPSolutions\AmznSellingPartnerApi\Models\ModelInterface;
use \MPSolutions\AmznSellingPartnerApi\ObjectSerializer;

/**
 * FfIPrepInstruction Class Doc Comment
 *
 * @category Class
 * @description Preparation instructions for shipping an item to Amazon&#39;s fulfillment network. For more information about preparing items for shipment to Amazon&#39;s fulfillment network, see the Seller Central Help for your marketplace.
 * @package  MPSolutions\AmznSellingPartnerApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class FfIPrepInstruction
{
    /**
     * Possible values of this enum
     */
    public const POLYBAGGING = 'Polybagging';
    public const BUBBLE_WRAPPING = 'BubbleWrapping';
    public const TAPING = 'Taping';
    public const BLACK_SHRINK_WRAPPING = 'BlackShrinkWrapping';
    public const LABELING = 'Labeling';
    public const HANG_GARMENT = 'HangGarment';
    
	/**
     * if `true` - throws error on deserialization,
     * when enum value is not allowed. Default behavior like `true`
     * if `false` - skips error for unexpected value
     */
    const STRICT_DESERIALIZATION = false;
	
	/**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::POLYBAGGING,
            self::BUBBLE_WRAPPING,
            self::TAPING,
            self::BLACK_SHRINK_WRAPPING,
            self::LABELING,
            self::HANG_GARMENT
        ];
    }
	
	/**
     * Gets strict|soft mode for deserialization
     * @return bool
     */
    public static function skipOnDeserialization()
    {
        return !self::STRICT_DESERIALIZATION;
    }
}


