<?php
/**
 * FfI20240320PrepCategory
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  MPSolutions\AmznSellingPartnerApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * The Selling Partner API for FBA inbound operations.
 *
 * The Selling Partner API for Fulfillment By Amazon (FBA) Inbound. The FBA Inbound API enables building inbound workflows to create, manage, and send shipments into Amazon's fulfillment network. The API has interoperability with the Send-to-Amazon user interface.
 *
 * The version of the OpenAPI document: 2024-03-20
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.0.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace MPSolutions\AmznSellingPartnerApi\Models\FulfillmentInbound20240320;
use \MPSolutions\AmznSellingPartnerApi\Models\ModelInterface;
use \MPSolutions\AmznSellingPartnerApi\ObjectSerializer;

/**
 * FfI20240320PrepCategory Class Doc Comment
 *
 * @category Class
 * @description The preparation category for shipping an item to Amazon&#39;s fulfillment network.
 * @package  MPSolutions\AmznSellingPartnerApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class FfI20240320PrepCategory
{
    /**
     * Possible values of this enum
     */
    public const ADULT = 'ADULT';
    public const BABY = 'BABY';
    public const FC_PROVIDED = 'FC_PROVIDED';
    public const FRAGILE = 'FRAGILE';
    public const GRANULAR = 'GRANULAR';
    public const HANGER = 'HANGER';
    public const LIQUID = 'LIQUID';
    public const PERFORATED = 'PERFORATED';
    public const SET = 'SET';
    public const SHARP = 'SHARP';
    public const SMALL = 'SMALL';
    public const TEXTILE = 'TEXTILE';
    public const UNKNOWN = 'UNKNOWN';
    public const NONE = 'NONE';
    
	/**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::ADULT,
            self::BABY,
            self::FC_PROVIDED,
            self::FRAGILE,
            self::GRANULAR,
            self::HANGER,
            self::LIQUID,
            self::PERFORATED,
            self::SET,
            self::SHARP,
            self::SMALL,
            self::TEXTILE,
            self::UNKNOWN,
            self::NONE
        ];
    }
}


