<?php
/**
 * FnnDefaultApiTest
 * PHP version 7.2
 *
 * @category Class
 * @package  MPSolutions\AmznSellingPartnerApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Selling Partner API for Finances
 *
 * The Selling Partner API for Finances helps you obtain financial information relevant to a seller's business. You can obtain financial events for a given order, financial event group, or date range without having to wait until a statement period closes. You can also obtain financial event groups for a given date range.
 *
 * The version of the OpenAPI document: v0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.1.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace MPSolutions\AmznSellingPartnerApi\Test\Api;

use \MPSolutions\AmznSellingPartnerApi\Configuration;
use \MPSolutions\AmznSellingPartnerApi\ApiException;
use \MPSolutions\AmznSellingPartnerApi\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * FnnDefaultApiTest Class Doc Comment
 *
 * @category Class
 * @package  MPSolutions\AmznSellingPartnerApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class FnnDefaultApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for listFinancialEventGroups
     *
     * .
     *
     */
    public function testListFinancialEventGroups()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listFinancialEvents
     *
     * .
     *
     */
    public function testListFinancialEvents()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listFinancialEventsByGroupId
     *
     * .
     *
     */
    public function testListFinancialEventsByGroupId()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listFinancialEventsByOrderId
     *
     * .
     *
     */
    public function testListFinancialEventsByOrderId()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
