<?php
/**
 * VDPVendorInvoiceApiTest
 * PHP version 7.2
 *
 * @category Class
 * @package  MPSolutions\AmznSellingPartnerApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Selling Partner API for Direct Fulfillment Payments
 *
 * The Selling Partner API for Direct Fulfillment Payments provides programmatic access to a direct fulfillment vendor's invoice data.
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.1.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace MPSolutions\AmznSellingPartnerApi\Test\Api;

use \MPSolutions\AmznSellingPartnerApi\Configuration;
use \MPSolutions\AmznSellingPartnerApi\ApiException;
use \MPSolutions\AmznSellingPartnerApi\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * VDPVendorInvoiceApiTest Class Doc Comment
 *
 * @category Class
 * @package  MPSolutions\AmznSellingPartnerApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class VDPVendorInvoiceApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for submitInvoice
     *
     * .
     *
     */
    public function testSubmitInvoice()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
